### ISSUE TITLE
Only 20 houses in Nestoria's results

### ISSUE THREAD

**Issue by veronicahs** [gaskyk/housing-websites#1]
Hi!!
Thank you very much for your code!!
I am really interested in your access to Nestoria's API. I am running it but I can only get at maximum 20 results. I have generated a csv file and every house appears duplicated. Could you help me fixing it? :)

**Comment by gaskyk** [comment]
Hi @veronicahs ! I'm really pleased someone has used this! That sounds odd. I wrote this code a while ago so maybe the API has changed since then. I'll take a look

**Comment by gaskyk** [comment]
Hi @veronicahs !
The Nestoria API defaults to 20 properties per API call, so I've added `&number_of_results=50` to get the maximum allowed 50 properties per API call in a new commit to the code just now.
The code should loop through all results pages for an area by using `&page=`, plus 1, 2, 3 etc. but it looks like the API is broken because the results of:
https://api.nestoria.co.uk/api?encoding=json&pretty=1&action=search_listings&country=uk&place_name=brighton&listing_type=buy&page=2 should equal the results from this:
https://www.nestoria.co.uk/brighton/property/buy/2
And they only seem to do that for the first page. I have fed this bug back to Nestoria through their website.

**Comment by veronicahs** [comment]
Thank you very much!!!!
I have done some calls to the API and it seems around 5-10% of the properties get lost. Maybe it is because that bug you mention.

Thanks again!! 

And please let me know!

**Comment by gaskyk** [comment]
Thanks @veronicahs ! Yes I think that until Nestoria fixes the API, there will only be a maximum of 50 unique properties returned for each area entered. So that % lost will depend on how big the area you're searching for is. In the example above, because Brighton is quite large, a lot of properties would be lost.
So I'll close the issue because I've fixed what I can, have raised the issue through the Nestoria website, and the code will work once their API is fixed.
But feel free to re-open the issue if you disagree.
Thanks!!
